config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount ActionCable.server => '/cable'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'
  get 'home/index'

  resources :conversations, only: [:create] do
    member do
        post :close
    end
  resources :messages, only: [:create]
end

  resources :projects do
    collection do
      get :mypage
    end
    member do
      get :recovery
      get :project_posts
    end
  end
  resources :posts do
    collection do
      get :search
    end
  end
  resources :comments
  resources :messages
  resources :functions do
    member do
      get :set_state
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment
  acts_as_mentioner

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  acts_as_commentable

  acts_as_mentioner
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :project
  
  validates_uniqueness_of :project_id
  
  scope :between, -> (project_id) do where(project_id: project_id) end
  
  def self.get(project_id)
    conversation = between(project_id).first
    return conversation if conversation.present?
    # create(sender_id: sender_id, recipient_id: recipient_id)
  end
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/function.rb
class Function < ApplicationRecord
  include AASM
  # acts_as_list

  acts_as_taggable_on :tags
  acts_as_taggable_on :users

  belongs_to :project

  aasm do
    state :to_do, initial: true
    state :in_progress 
    state :complete
    state :feedback
    state :end

    event :progress  do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :in_progress, success: :set_progress_date
    end

    event :complete do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :complete, success: :set_complete_date
    end

    event :feedback do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :feedback, success: :set_feedback_date
    end

    event :finish do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :end, success: :set_finish_date
    end
  end
  private 

  def set_progress_date
    update in_progress_updated_at: Time.zone.now
  end

  def set_complete_date
    update complete_updated_at: Time.zone.now
  end

  def set_feedback_date
    update feedback_updated_at: Time.zone.now
  end

  def set_finish_date
    update end_updated_at: Time.zone.now
  end
  
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_commentable

  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :project
  has_many :comments

  acts_as_taggable_on :participant

  acts_as_commentable
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :functions, dependent: :destroy
  has_one :conversation, dependent: :destroy

  enum project_status: %i(not_started in_progress complete)

  after_create :create_conversation

  def create_conversation
    Conversation.create(project_id: self.id)
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  USER_COLUMNS = %i(name phone user_type)
  
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :comments

  has_many :posts
  enum user_type: [:developer, :customer]

  acts_as_mentionable
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable, only: %i(create)
  before_action :load_comment, only: %i(destroy)
  
  def create
    byebug
    mentionee = []
    mention_email = []
    name_pattern = /[@|\s@][가-힣]\s[가-힣][가-힣]/
    extracted_names = params[:comment][:comment].scan(name_pattern)
    extracted_names.each do |name| mentionee << name[1..] end
    if mentionee.size != 0
      @comment = @commentable.comments.new
      @comment.comment =''
      mentionee.each do |name| 
        @comment.mention!(User.find_by(name: name))
        mention_email << User.find_by(name: name).email
      end
      params[:comment][:comment].each_char do |char|
        if char != '@'
          @comment.comment += char 
        end
      end
      @comment.commentable_id = params[:comment][:commentable_id]
      @comment.commentable_type = params[:comment][:commentable_type]
      @comment.user_id = params[:comment][:user_id]
      @comment.save
      UserMailer.send_comment_mentioned_email(mention_email, @comment).deliver
    else
      @comment = @commentable.comments.create comment_params
    end
  end

  def destroy
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :commentable_id, :commentable_type, :user_id, mention_attributes: [:mentionable_id])
  end

  def load_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def load_commentable
    # pass 순서
    # post/show.html.erb에서 local로 commentable = @post
    # _new.html.erb에서 commentable.id가 넘어온다
    @commentable = Post.find_by(id: params[:comment][:commentable_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="box-<%= comment.id %>">
  <div id="comment-list-<%=comment.id%>">
    <hr/>
    <h6 style="color: navy"><%=User.find_by(id: comment.user_id).name%></h6>
    <small style="color:grey;"><%=pretty_date(comment.created_at)%></small>
    <p></p>
    <p><%=comment.comment%></p>
  </div> 
  <p style="text-align:right">
    <%= link_to comment_path(comment.id), method: :delete, remote: true do %>
      <button type="button" class="btn btn-secondary btn-sm">삭제</button>
    <%end%>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment ||= Comment.new, method: :post, remote: true do |f|%>
  <div class="form-group">
    <%= f.text_area :comment, id: "input_form", class: "form-control", placeholder: "입력 란" %>
    <%= f.hidden_field :commentable_type, value: "Posts" %>
    <%= f.hidden_field :commentable_id, value: commentable.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <p></p>
    <%= f.fields_for :mention, Mention.new do |mention_attribute| %>
      <%= mention_attribute.select :mentionable_id, 
        User.all.map{|user| [user.name, user.id]},
        class: 'form-control',
        id: 'select-mentionable'
      %>
    <%end%>
  </div>
  <%= f.submit "입력", class: "btn btn-primary btn-md" %>
<% end %>

<script>
$('#select-mentionable').select2({
    placeholder: 'Select mentionee'
});
$('#select-mentionable').on('select2:select', function(e){
  var id = e.params.data.id;
  var value = $(this).val();
});
</script>

app/views/comments/_show.html.erb
<div id="box-<%= comment.id %>">
  <div id="comment-list-<%=comment.id%>">
    <hr/>
    <h6 style="color: navy"><%=User.find_by(id: comment.user_id).name%></h6>
    <small style="color:grey;"><%=pretty_date(comment.created_at)%></small>
    <p></p>
    <p><%=comment.comment%></p>
  </div> 
  <p style="text-align:right">
    <%= link_to edit_comment_path(comment.id), remote: true do%>
      <button type="button" class="btn btn-secondary btn-sm">수정</button>
    <%end%>
    <%= link_to comment_path(comment.id), method: :delete, remote: true do %>
      <button type="button" class="btn btn-secondary btn-sm">삭제</button>
    <%end%>
  </p>
</div>

app/views/comments/create.js.erb
var html = "<%= j(render(partial: 'comments/comment', locals: {comment: @comment})) %>"
$("#new_comment").val("")
$("#comment-list").append(html)

app/views/comments/destroy.js.erb
$("#box-<%= @comment.id %>").remove()