config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount ActionCable.server => '/cable'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'
  get 'home/index'

  resources :conversations, only: [:create] do
    member do
        post :close
    end
  resources :messages, only: [:create]
end

  resources :projects do
    collection do
      get :mypage
    end
    member do
      get :recovery
      get :project_posts
    end
  end
  resources :posts do
    collection do
      get :search
    end
  end
  resources :comments
  resources :messages
  resources :functions do
    member do
      get :set_state
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment
  acts_as_mentioner

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  acts_as_commentable

  acts_as_mentioner
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :project
  
  validates_uniqueness_of :project_id
  
  scope :between, -> (project_id) do where(project_id: project_id) end
  
  def self.get(project_id)
    conversation = between(project_id).first
    return conversation if conversation.present?
    # create(sender_id: sender_id, recipient_id: recipient_id)
  end
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/function.rb
class Function < ApplicationRecord
  include AASM
  # acts_as_list

  acts_as_taggable_on :tags
  acts_as_taggable_on :users

  belongs_to :project

  aasm do
    state :to_do, initial: true
    state :in_progress 
    state :complete
    state :feedback
    state :end

    event :progress  do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :in_progress, success: :set_progress_date
    end

    event :complete do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :complete, success: :set_complete_date
    end

    event :feedback do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :feedback, success: :set_feedback_date
    end

    event :finish do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :end, success: :set_finish_date
    end
  end
  private 

  def set_progress_date
    update in_progress_updated_at: Time.zone.now
  end

  def set_complete_date
    update complete_updated_at: Time.zone.now
  end

  def set_feedback_date
    update feedback_updated_at: Time.zone.now
  end

  def set_finish_date
    update end_updated_at: Time.zone.now
  end
  
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_commentable

  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :project
  has_many :comments

  acts_as_taggable_on :participant

  acts_as_commentable
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :functions, dependent: :destroy
  has_one :conversation, dependent: :destroy

  enum project_status: %i(not_started in_progress complete)

  after_create :create_conversation

  def create_conversation
    Conversation.create(project_id: self.id)
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  USER_COLUMNS = %i(name phone user_type)
  
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :comments

  has_many :posts
  enum user_type: [:developer, :customer]

  acts_as_mentionable
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agileboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <style>
      body {
        /* background-color: rgb(242, 242, 242); */
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }
      .color-primary {
        color: rgb(7, 3, 130) !important;
      }
      .btn-primary {
        color: #fff !important;
        background-color: rgb(7, 3, 130) !important;
        border-color: rgb(7, 3, 130) !important;
        min-height: 40px !important;
      }
      .btn-primary:hover {
        color: #fff !important;
        background-color: rgb(7, 3, 130) !important;
        border-color: rgb(7, 3, 130) !important;
      }
      .btn-primary:focus, .btn-primary.focus {
        box-shadow: 0 0 0 2px rgb(7, 3, 130) !important;
      }
      .container {
        max-width: 1240px !important;
      }
      .text-gray {
        color: gray;
      }
      .alert-container {
        margin: 0 auto;
        max-width: 1100px;
      }
      .alert-notification {
        position: fixed;
        width:inherit;
        max-width:inherit;
        z-index: 1000;
        padding: 0.75rem 1.25rem;
        margin-top: 0.3rem;
        opacity: 0.9;
        margin-bottom: 1rem;
        border: 1px solid transparent;
        border-radius: 3px;
      }
      .fs-14 {
        font-size: 14px;
      }
    </style>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= tinymce_assets %>
    <div class="container alert-container">
      <% if notice %>
        <div class="alert alert-notification alert-success">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-notification alert-danger">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        </div>
      <% end %>
    </div>
    
    <%= yield %>

    <script type="text/javascript">
      <% if notice.present? || alert.present? %>
        $(function() {
          $(".alert-notification").fadeTo(3000, 0.9).slideUp(500, function(){
            $(".alert-notification").alert('close');
          })
        })
      <% end %>
    </script>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="text-white mt-5 p-2" style="background-color: rgb(9, 23, 41) !important;">
  <div class="container">
    <div class="row d-flex">
      <div class="col-lg-8 col-sm-12  mt-2 mb-2 text-left ">
        Copyright © 2020 Ajou Dev Team
      </div>
      <div class="col-lg-4 col-sm-12 ml-auto mb-2 mt-2">
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<style>
  .font-nav {
    color: rgb(206, 206, 206) !important;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light pl-4 py-3" style="background-color: black !important;">
  <img src="/image/logo.png" class="mr-2" style="width: 30px; height: 30px;" alt="">
  <a class="navbar-brand font-weight-bold font-nav" href="/">Broken Sunset</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active mr-3">
        <a class="nav-link font-nav" href="/">홈 <span class="sr-only">(current)</span></a>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown mr-3">
          <a class="nav-link dropdown-toggle font-nav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            게시판
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "게시글 보기", posts_path, class: "dropdown-item" %>
            <%= link_to "게시글 생성", new_post_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown mr-3">
          <a class="nav-link dropdown-toggle font-nav" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            프로젝트 게시판 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "프로젝트 생성", new_admin_project_path, class: "dropdown-item" %>
            <%= link_to "프로젝트 보기", projects_path, class: "dropdown-item" %>
            <%= link_to "기능 생성", new_function_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item mr-3">
          <div class="nav-link font-nav"><%= current_user.email %>님</div>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "nav-link font-nav" %>
        </li>
      <% else %>
        <li class="nav-item mr-3">
          <%= link_to "로그인", new_user_session_path, class: "nav-link font-nav" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "회원가입", new_user_registration_path, class: "nav-link font-nav" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_input.html.erb
<% placeholder ||= "입력하세요" %>

<div class="form-group">
  <%= f.label name %>
  <%= f.send(type, name, {placeholder: placeholder}) %>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="function-modal-<%= @function.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= @function.id %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "functions/form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_option_for_select.html.erb
<%= f.select columns , options_for_select(User.all.map {|u| [u.name, u.id]}),{},{multiple: true , class: "form-control mb-3"}%>

app/views/shared/_section.html.erb
<% title ||= "제목" %>
<div class="text-center my-5">
  <h5 class="font-bold mb-3">Broken Sunset</h5>
  <h2 class="font-bold"><%= title %></h2>
</div>