config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  mount ActionCable.server => '/cable'
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'
  get 'home/index'

  resources :conversations, only: [:create] do
    member do
        post :close
    end
  resources :messages, only: [:create]
end

  resources :projects do
    collection do
      get :mypage
    end
    member do
      get :recovery
      get :project_posts
    end
  end
  resources :posts do
    collection do
      get :search
    end
  end
  resources :comments
  resources :messages
  resources :functions do
    member do
      get :set_state
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment
  acts_as_mentioner

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at DESC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  acts_as_commentable

  acts_as_mentioner
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :project
  
  validates_uniqueness_of :project_id
  
  scope :between, -> (project_id) do where(project_id: project_id) end
  
  def self.get(project_id)
    conversation = between(project_id).first
    return conversation if conversation.present?
    # create(sender_id: sender_id, recipient_id: recipient_id)
  end
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/function.rb
class Function < ApplicationRecord
  include AASM
  # acts_as_list

  acts_as_taggable_on :tags
  acts_as_taggable_on :users

  belongs_to :project

  aasm do
    state :to_do, initial: true
    state :in_progress 
    state :complete
    state :feedback
    state :end

    event :progress  do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :in_progress, success: :set_progress_date
    end

    event :complete do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :complete, success: :set_complete_date
    end

    event :feedback do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :feedback, success: :set_feedback_date
    end

    event :finish do
      transitions from: [:to_do, :in_progress, :complete, :feedback, :end], to: :end, success: :set_finish_date
    end
  end
  private 

  def set_progress_date
    update in_progress_updated_at: Time.zone.now
  end

  def set_complete_date
    update complete_updated_at: Time.zone.now
  end

  def set_feedback_date
    update feedback_updated_at: Time.zone.now
  end

  def set_finish_date
    update end_updated_at: Time.zone.now
  end
  
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_commentable

  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :project
  has_many :comments

  acts_as_taggable_on :participant

  acts_as_commentable
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :functions, dependent: :destroy
  has_one :conversation, dependent: :destroy

  enum project_status: %i(not_started in_progress complete)

  after_create :create_conversation

  def create_conversation
    Conversation.create(project_id: self.id)
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  USER_COLUMNS = %i(name phone user_type)
  
  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :comments

  has_many :posts
  enum user_type: [:developer, :customer]

  acts_as_mentionable
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: %i(show)
  before_action :check_owner, only: %i(show)

  def index 
    @projects = Project.all
  end 
  
  def show
    # 채팅방 로드
    session[:conversations] ||= []
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:project, :messages).find(session[:conversations])

    @functions = @project.functions.page(params[:page]).per(10)
    @function_per_user = []
    @project.users.each do |user|
      @function_per_user << [user.name, @project.functions.tagged_with(user.id).count ]
    end

    @sort = @functions.ransack(params[:q])
    @sort_functions = @sort.result
    @time_hash = Hash.new
    @time_arr = []
    count = [@project.functions.all.count,0,0,0,0]
    @state_arr = [:to_do_updated_at,:in_progress_updated_at,:complete_updated_at,:feedback_updated_at,:end_updated_at]
    hash_n= Hash[*@state_arr.zip(count).flatten]
    @date_arr = (1.month.ago.to_date..Date.today).to_a
    (1.month.ago.to_date..Date.today).to_a.each do |time|
      @time_arr.push(calculate_count(@project.functions,hash_n,time.to_time))
    end
    @result = Hash.new
    @temp = []
    @res = []
    # @date_arr.each do |da, index|
    #   @time_arr.pluck(sa)
    #   # @result[da] = @time_arr.pluck(sa)
    # end
    # @date_arr.each do |da|   
    @state_arr.each do |sa|
        # @temp.push([sa,@time_arr.pluck(sa)[@date_arr.index(da)]])
        
      @result[:name] = sa
      @result[:data] = Hash[*@date_arr.zip(@time_arr.pluck(sa)).flatten]
      @res.push(@result.clone)
    end
      # @result[:data] = @temp.clone
      # @temp = []
      # @result.push({ sa => @date_arr.zip(@time_arr.pluck(sa)) })
    # end
    
    # @result = [*@date_arr.zip(@time_arr.pluck(:to_do_updated_at))]
      # @time_hash[time] = calculate_count(@project.functions,hash_n,time.to_time).to_a
    # # end
    # @result = Hash.new
    # @state_arr.each do |sa|
    #   @result[sa] = [*@date_arr.zip(@time_arr.pluck(sa))]
    #   @result[sa] = 
    # end
  
    # @time_hash = calculate_count(@project.functions,hash_n)
    # @xth = @time_hash.keys
    # @yth = @time_hash.values
  end

  private 

  def load_project
    @project = Project.find_by(id: params[:id])
  end 

  def check_owner
    unless @project.users.include?(current_user)
      redirect_to root_path, alert: "접근권한이 없습니다"
    end
  end

  def calculate_count(functions,h,date)
    new_hash = Hash.new
    cnt = 0
    cnt2 = 0
    functions.each do |function|
      @state_arr.each do |state_updated_at|
        if (function[state_updated_at] - date).to_i == 0 
          case state_updated_at
          when :to_do_updated_at
            then  
          else
            h[state_updated_at] += 1 
            h[@state_arr[@state_arr.index(state_updated_at)-1]] -= 1
            cnt += 1
          end
        end
      end
      new_hash = h.clone
    end
    return new_hash
  end

  # def calculate_count(functions,state_updated_at, date)
  #   count = 0
  #   functions.all.each do |function|
  #     if function.state_updated_at - date == 0 
  #       if state_updated_at == to_do_updated_at
  #         count -= 1 
  #       else
  #         count += 1
  #       end
  #     end
  #   end
  #   return count
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_assign_info.html.erb
<% user_list = project.users %>
<div class="row">
  <div class="col-4">
    <div class="my-5 text-center">개발자별 태스크 수</div>
    <%= pie_chart @function_per_user %>
  </div>
  <div class="col-8">
    <div class="my-5 text-center">상태별 개발자 태스크 수</div>
    <% arr = []%>
    <% change_arr = []%>
    <% new_arr = Function.aasm.states.map(&:name)%>
    <% new_arr.each do |key|%>
      <% change_arr.push(I18n.t(key)) %>
    <% end %>
    <% new_hash = Hash[*new_arr.zip(change_arr).flatten] %>
    <% user_list.each do |user| %>
      <% h = Hash.new %>
      <% h[:name] = user.name %>
      <% h[:data] = project.functions.tagged_with(user.id).group(:aasm_state).count.transform_keys{|k| k.to_sym} %>
      <% h[:data].transform_keys!(&new_hash.method(:[])) %>
      <% arr.push(h)%>
    <% end %>
    <%= column_chart arr %>
  </div>
</div>

app/views/projects/_project.html.erb
<style>
  .project-image {
    min-height: 400px; 
    max-width:100%; 
    max-height:100%; 
    background-size: cover; 
    background-position: center;
    position: relative;
  }
  .project-name{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
  }
</style>

<div class="col-12 col-md-6 col-lg-4 d-flex flex-column bg-cover p-1">
  <%= link_to project_path(project), class: "text-white" do %>
    <div class="card project-image" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('<%= project.image %>');">
      <div class="card-body mt-auto mb-n11 py-8">
        <h2 class="project-name font-weight-bolder">
          <%= project.name %>
          <%# fa_icon "chevron-right", text: "", right: true %>
        </h2>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_status_info.html.erb
<% project ||= nil %>
<div class="row mt-3">
  <div class="col-4 pr-0 justify-content-flex-center py-2 px-5">
    <div class="card">
      <img class="card-img-top" src="<%= project.image.url %>" alt="Card image cap">
      <div class="card-body">
        <h6 class="card-title"><%= project.name %></h6>
        <div class="row justify-content-between px-3 fs-14">
          <div class="text-gray">참여 인원</div>
          <div><%= project.users.count %>명</div>
        </div>
        <div class="row justify-content-between px-3 fs-14">
          <div class="text-gray">프로젝트 시작일</div>
          <div><%= pretty_date project.start_at %></div>
        </div>
        <div class="row justify-content-between px-3 fs-14">
          <div class="text-gray">프로젝트 마감일</div>
          <div><%= pretty_date project.end_at %></div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="row justify-content-between px-3 fs-14">
            <div class="text-gray">진행 기간</div>
            <div><%= (Date.today - project.start_at.to_date).to_i %>일</div>
          </div>
          <div class="row justify-content-between px-3 fs-14">
            <div class="text-gray">진행 기간</div>
            <div><%= (project.end_at.to_date - Date.today).to_i %>일</div>
          </div>
        </li>
      </ul>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="row justify-content-between px-3 fs-14">
            <div class="text-gray">진행도</div>
            <div><%= (project.functions.end.count * 100 / project.functions.count) %>%</div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="col-8 pl-0">
    <div class="mt-2 mb-3 text-center">프로젝트 태스크 현황</div>
    <%= bar_chart(시작전: project.functions.to_do.count, 진행중: project.functions.in_progress.count, 완료: project.functions.complete.count, 피드백: project.functions.feedback.count, 종료: project.functions.end.count) %>
  </div>
</div>

app/views/projects/index.html.erb
<section>
  <div class="container my-4">
    <div class="text-center my-5">
      <h5 class="font-bold mb-3">Broken Sunset</h5>
      <h2 class="font-bold">Select your Project</h2>
    </div>
    <div class="row no-gutters d-block d-lg-flex flickity flickity-lg-none" data-flickity="{&quot;watchCSS&quot;: true}">
      <% @projects.each do |project| %>
        <%= render "project", project: project %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<style>
.project-conversations {
  border: 1px solid #ededed;
}
</style>

<%= render 'shared/section',title: "Project Dashboard" %>
<div class="container bg-white p-3 mb-3">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#status">프로젝트 개발 현황</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#process">개발 추이</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#assign">개발자별 할당량</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="status">
      <%= render "status_info", project: @project %>
    </div>
    <div class="tab-pane fade" id="process">
      <%# <%= line_chart @functions.group(:aasm_state).group_by_day(:start_at, last: 30).count, xtitle: "date", ytitle: "value" %> 
      <%# <%= line_chart @time_hash.group(:key), xtitle: "date", ytitle: "value" %>
      <%# <%= @time_arr.pluck(:to_do_updated_at) %>
     <div class="my-5 text-center">상태별 날짜 당 기능 수</div>
      <%= line_chart @res %> 
    </div>
    <div class="tab-pane fade" id="assign">
      <%= render "assign_info", project: @project %>
    </div>
  </div>
  <!-- 통계 항목 -->

  <!-- 기능 항목 -->
  <%= render "functions/functions" %>

  <!-- 프로젝트 채팅 -->
  <div>
    <h5 class="mt-5 mb-2">채팅방</h5>
    <div class="project-conversations">
      <div class="col-md-12">
        <ul id="conversations-list">
          <% @conversations.each do |conversation| %>
            <%= render 'conversations/conversation', conversation: conversation %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<script>
  $(function(){
    Rails.ajax({
      url: "<%= conversations_path(project_id: @project.id) %>",
      type: "POST",
      success: function(data) {
        console.log("load chatting room...")
      },
      error: function(data) {}
    });
  })
</script>